services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Ensure volume name matches

  backend:
    build: ./task-backend
    container_name: backend_api
    restart: always
    depends_on:
      - postgres
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: todo_app
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "3001:3001"

  frontend:
    build: ./task-frontend
    container_name: frontend_app
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:  # Make sure this is defined
